"""Validate the real-API tool-selection fixture against the real bridge and services.

The fixture (``fixtures/demo_transcript.json``) was generated by a real Claude sub-agent
choosing tools from the project's actual descriptions. This test closes the loop
deterministically: the model's chosen tools exist in the bridge, and dispatching its chosen
calls against the real services returns the expected records -- proving the description-driven
choices are not just plausible but correct.
"""

from __future__ import annotations

import asyncio
import json

from mcp_governance.bridge import build_bridge
from mcp_governance.config import FIXTURES_DIR

FIXTURE = FIXTURES_DIR / "demo_transcript.json"


def test_fixture_choices_are_real_tools_and_dispatch_correctly() -> None:
    data = json.loads(FIXTURE.read_text())
    bridge = asyncio.run(build_bridge())

    s1 = data["scenario_1"]
    assert s1["chosen_tool"] == "get_claim"
    assert s1["chosen_tool"] in bridge.tool_names()
    result = bridge.dispatch(s1["chosen_tool"], s1["tool_input"])
    assert result["found"] is True
    assert result["claim_id"] == "CLM-10001"

    s2 = data["scenario_2"]
    assert s2["chosen_tool"] == "search_claims"
    assert s2["chosen_tool"] in bridge.tool_names()
    result2 = bridge.dispatch(s2["chosen_tool"], s2["tool_input"])
    assert result2["found"] is True
    for claim in result2["claims"]:
        assert claim["status"] == "under_review"
        assert claim["amount"] >= 10000
